export const CHANGE_POSITION = 'CHANGE_POSITION'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const UPDATE_DATA = 'UPDATE_DATA'
export const CHANGE_PHONE_PRODUCER = 'CHANGE_PHONE_PRODUCER'
export const CHANGE_TABLET_PRODUCER = 'CHANGE_TABLET_PRODUCER'